### PR TITLE
Fixes #23

### LINKED ISSUE #23: Unable to collect stats
**Snap daemon version** (use `snapteld -v`): latest

**Environment**:
OS: Linux
Arch: x86_64

I created a database and attempted to send the collected metrics to it.

**What happened**:
The parser throws the error "database is not unique"
img

**What you expected to happen**:
[This](https://www.dropbox.com/s/00t0wd5iq0kgt6p/show_stats_response.json?raw=1) response from influxdb (`show stats`) is valid and should be handled.  Notice the series with the name that starts with 'tsm1' and how they are not unique.

**Steps to reproduce it** (as minimally and precisely as possible):

1. create a database
2. publish metrics to it
3. create a task that collects influx stats

**Anything else do we need to know** (e.g. issue happens only occasionally):

### PR DESCRIPTION
**Pull request by jcooklin**
Fixes #23 

Summary of changes:
- [x] Added structs for deserializing stats and diagnostics
- [x] tests 

Testing done:
- Manual

### CODE REVIEW

File: influxdb/influxdb.go [hunk 1]
```diff
@@ -50,100 +52,84 @@ const (
...
+type influxdbCollector struct {
+	urlStatistic  *url.URL
+	urlDiagnostic *url.URL
+	getResponse
 }
 
-type datum struct {
-	value interface{}
-	tags  map[string]string
+type endpoint interface {
```
Comment (mkleina) [inline influxdb/influxdb.go]: The endpoint interface isn't used anywhere in code or unit tests, so it can be removed.

Comment (mkleina) [inline influxdb/influxdb.go]: The endpoint interface isn't used anywhere in code or unit tests, so it can be removed.

**Comment by jcooklin** [comment]
Thanks for the review @mkleina.  Anything else catch your 👁 ?
